version: "3.9"
services:
  db:
    image: postgres:12.3
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=2GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_PASSWORD: "qwerty555"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 54322:5432
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres
  frontend:
    image: testjava:1
    container_name: appfrontend
    ports:
      - 80:80
    environment:
      POSTGRES_HOST: db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    links:
      - db
    networks:
      - postgres
volumes:
  pgdata:
networks:
  postgres:
    driver: bridge