name: build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildservice:
    name: Сборка
    runs-on: ubuntu-latest
    steps:
    - name: Получаем доступ к репозиторию
      uses: actions/checkout@v2     
      with:
        path: service
    - name: Читаем настройки docker
      uses: madhead/read-java-properties@latest
      id: docker
      with:
        file: service/docker.properties
        all: true
    - name: Устанавливаем JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven 
#    - name: build root
#      run: mvn -B package --file service/pom.xml
    - name: Логин к dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Сборка образа
      uses: docker/build-push-action@v2
      with:
        context: ./service
        push: true
        tags: |
          fedormoore/${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}
          fedormoore/${{ steps.docker.outputs.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ARTIFACT_NAME=${{ steps.docker.outputs.ARTIFACT_NAME }}
          IMAGE_VERSION=${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}
#    - name: Docker Hub Description
#      uses: peter-evans/dockerhub-description@v2
#      env:
#        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        DOCKERHUB_REPOSITORY: fedormoore/${{ steps.docker.outputs.IMAGE_NAME }}
